/** Mots-clés pour l'extraction du domaine */

export const DOMAIN_KEYWORDS = [
    // ===== Sciences exactes et ingénierie =====
    "Engineering",
    "Computer Science",
    "Data Science",
    "Artificial Intelligence",
    "Machine Learning",
    "Robotics",
    "Software Engineering",
    "Information Technology",
    "Cybersecurity",
    "Network Engineering",
    "Telecommunications",
    "Electronics",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Aerospace Engineering",
    "Automotive Engineering",
    "Industrial Engineering",
    "Chemical Engineering",
    "Biomedical Engineering",
    "Materials Science",
    "Nanotechnology",
    "Physics",
    "Astrophysics",
    "Quantum Physics",
    "Chemistry",
    "Biochemistry",
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Analytical Chemistry",
    "Environmental Chemistry",
    "Biology",
    "Molecular Biology",
    "Cell Biology",
    "Genetics",
    "Genomics",
    "Bioinformatics",
    "Neuroscience",
    "Zoology",
    "Botany",
    "Microbiology",
    "Ecology",
    "Evolutionary Biology",
    "Marine Biology",
    "Biotechnology",
    "Pharmacology",
    "Toxicology",
    "Immunology",
    "Epidemiology",
    "Public Health",
    "Health Sciences",
    "Medicine",
    "Dentistry",
    "Pharmacy",
    "Veterinary Science",
    "Nursing",
    "Physiotherapy",
    "Radiology",
    "Pathology",
    "Cardiology",
    "Oncology",
    "Pediatrics",
    "Geriatrics",
    "Psychiatry",
    "Forensic Science",

    // ===== Mathématiques et statistiques =====
    "Mathematics",
    "Applied Mathematics",
    "Pure Mathematics",
    "Statistics",
    "Biostatistics",
    "Econometrics",
    "Actuarial Science",
    "Operations Research",
    "Optimization",

    // ===== Sciences sociales et humaines =====
    "Social Sciences",
    "Humanities",
    "Sociology",
    "Anthropology",
    "Ethnology",
    "Archaeology",
    "History",
    "Art History",
    "Geography",
    "Urban Studies",
    "Political Science",
    "International Relations",
    "Diplomacy",
    "Economics",
    "Development Economics",
    "Behavioral Economics",
    "Psychology",
    "Clinical Psychology",
    "Cognitive Psychology",
    "Social Psychology",
    "Educational Psychology",
    "Linguistics",
    "Applied Linguistics",
    "Sociolinguistics",
    "Philology",
    "Translation Studies",
    "Communication",
    "Media Studies",
    "Journalism",
    "Public Relations",
    "Advertising",
    "Marketing",
    "Digital Marketing",
    "Business",
    "Business Administration",
    "MBA",
    "Management",
    "Strategic Management",
    "Human Resources",
    "Organizational Behavior",
    "Entrepreneurship",
    "Innovation",
    "Finance",
    "Corporate Finance",
    "Investment",
    "Risk Management",
    "Accounting",
    "Auditing",
    "Taxation",
    "Real Estate",
    "Logistics",
    "Supply Chain Management",
    "Project Management",
    "Tourism",
    "Hospitality",
    "Event Management",
    "Sports Management",

    // ===== Éducation et formation =====
    "Education",
    "Pedagogy",
    "Didactics",
    "Curriculum Studies",
    "Educational Leadership",
    "Higher Education",
    "Adult Education",
    "Special Education",
    "Teaching",
    "Teacher Training",
    "Instructional Design",

    // ===== Arts, lettres et design =====
    "Arts",
    "Fine Arts",
    "Visual Arts",
    "Performing Arts",
    "Theater",
    "Drama",
    "Film Studies",
    "Cinematography",
    "Photography",
    "Music",
    "Musicology",
    "Composition",
    "Conducting",
    "Literature",
    "Creative Writing",
    "Poetry",
    "Novel Writing",
    "Comparative Literature",
    "Philosophy",
    "Ethics",
    "Metaphysics",
    "Epistemology",
    "Theology",
    "Religious Studies",
    "Islamic Studies",
    "Buddhist Studies",
    "Jewish Studies",
    "Architecture",
    "Urban Design",
    "Landscape Architecture",
    "Interior Architecture",
    "Industrial Design",
    "Product Design",
    "Graphic Design",
    "Interaction Design",
    "User Experience (UX) Design",
    "User Interface (UI) Design",
    "Animation",
    "Game Design",
    "Fashion Design",
    "Textile Design",
    "Jewelry Design",

    // ===== Agriculture et environnement =====
    "Agriculture",
    "Agronomy",
    "Horticulture",
    "Viticulture",
    "Oenology",
    "Animal Science",
    "Veterinary Medicine",
    "Environmental Science",
    "Environmental Engineering",
    "Climate Science",
    "Atmospheric Science",
    "Oceanography",
    "Hydrology",
    "Water Resources",
    "Forestry",
    "Conservation Biology",
    "Sustainable Development",
    "Renewable Energy",
    "Solar Energy",
    "Wind Energy",
    "Bioenergy",
    "Nuclear Engineering",

    // ===== Droit et politique =====
    "Law",
    "International Law",
    "Human Rights Law",
    "Business Law",
    "Criminal Law",
    "Constitutional Law",
    "European Law",
    "Public Policy",
    "Public Administration",
    "Governance",
    "Political Economy",

    // ===== Domaines transversaux =====
    "Interdisciplinary Studies",
    "Liberal Arts",
    "General Studies",
    "Research Methods",
    "Criminal Justice",
    "Forensic Psychology",
    "Criminology",
    "Sustainability",
];

