name: Notify deadlines

on:
  schedule:
    - cron: '10 14 * * *' # Tous les jours à 8h00
  workflow_dispatch: # Permet de le lancer manuellement

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger notifications
        run: |
          curl -f -X POST https://next-api.qcdigitalhub.com/api/cron/notify-deadlines \
            -H "X-Cron-Secret: ${{ secrets.CRON_SECRET }}"